#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# variables
APP_VER=1.4.21
BEN_VER=1.0.18
APP_DIR=$MSMR_ROOT/apps/postfix

# working folder
cd $APP_DIR

# remove folders
rm -rf memcached-$APP_VER
rm -rf install
rm -rf libmemcached-$BEN_VER
rm -rf benchmark

# download and extract
if [ ! -f memcached-$APP_VER.tar.gz ]; then
    wget http://www.memcached.org/files/memcached-$APP_VER.tar.gz
fi
tar zxvf memcached-$APP_VER.tar.gz

# build
cd memcached-$APP_VER
mkdir ../install
./configure --prefix=$APP_DIR/install
make
make install


# download benchmark
cd ../
if [ ! -f libmemcached-$BEN_VER.tar.gz ]; then
    wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-$BEN_VER.tar.gz
fi
tar zxvf libmemcached-$BEN_VER.tar.gz


# build benchmark
cd libmemcached-$BEN_VER
mkdir ../benchmark
./configure --prefix=$APP_DIR/benchmark
make
make install

