#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# important benchmark source files in dkftpbench-0.45: ftp_client_pipe_test.cc ftp_client_pipe.cc Poller_bench.cc

# variables
APP_VER=1.3.5
BEN_VER=0.45
APP_DIR=$MSMR_ROOT/apps/proftpd

# download
cd $APP_DIR
rm -rf proftpd-$APP_VER
rm -rf install
if [ ! -f proftpd-$APP_VER.tar.gz ]; then
    wget ftp://ftp.proftpd.org/distrib/source/proftpd-$APP_VER.tar.gz
fi
tar zxvf proftpd-$APP_VER.tar.gz

# build
mkdir install
cd proftpd-$APP_VER
export install_user=$USER
export install_group=$USER
./configure --prefix=$APP_DIR/install
make
make install

# config virtual user and server
cd contrib/
./ftpasswd --passwd --name=ftpuser --home=$APP_DIR/install/data --shell=/bin/sh --uid=2000 --stdin <<< "ftpuser"
mv ftpd.passwd ../../install/etc
GROUP=$(id -gn)
cd ../../install
mkdir data
echo "Port 2121" >> proftpd.conf
echo "PidFile $APP_DIR/install/var/proftpd.pid" >> proftpd.conf
echo "WtmpLog off" >> proftpd.conf
echo "User $USER" >> proftpd.conf
echo "Group $GROUP" >> proftpd.conf
echo "ScoreboardFile $APP_DIR/install/var/proftpd.scoreboard" >> proftpd.conf
echo "DefaultRoot $APP_DIR/install/data" >> proftpd.conf
echo "RequireValidShell  off" >> proftpd.conf
echo "AuthUserFile  $APP_DIR/install/etc/ftpd.passwd" >> proftpd.conf
echo "SystemLog $APP_DIR/install/etc/proftpd.log" >> proftpd.conf
echo "<Limit LOGIN>" >> proftpd.conf
echo "AllowAll" >> proftpd.conf
echo "</Limit>" >> proftpd.conf
echo "<Directory $APP_DIR/install/data >" >> proftpd.conf
echo "<Limit WRITE READ STOR STOU>" >> proftpd.conf
echo "AllowAll" >> proftpd.conf
echo "</Limit>" >> proftpd.conf
echo "</Directory>" >> proftpd.conf
mv proftpd.conf ./etc

# benchmark
cd ../
rm -rf benchmark
rm -rf dkftpbench-$BEN_VER
if [ ! -f dkftpbench-$BEN_VER.tar.gz ]; then
    wget http://www.kegel.com/dkftpbench/dkftpbench-$BEN_VER.tar.gz
fi
tar zxvf dkftpbench-$BEN_VER.tar.gz
cd dkftpbench-$BEN_VER
patch -p1 < ../dkftpbench.patch
./configure --prefix=$APP_DIR/benchmark
make
make install

# benchmark generated data
make data
mv ./x10k.dat ../install/data/x10k.dat
mv ./x100k.dat ../install/data/x100k.dat
mv ./x1000k.dat ../install/data/x1000k.dat

