#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# benchmark pgbench source code in postgresql-9.3.5/contrib/pgbench/pgbench.c

# variables
APP_VER=9.3.5
APP_DIR=$MSMR_ROOT/apps/pgsql/${1}


# working folder
cd $APP_DIR


# remove folders
rm -rf postgresql-$APP_VER
rm -rf install


# download and extract
if [ ! -f postgresql-$APP_VER.tar.gz ]; then
    wget http://ftp.postgresql.org/pub/source/v9.3.5/postgresql-$APP_VER.tar.gz
fi
tar zxvf postgresql-$APP_VER.tar.gz


# build postgresql
cd postgresql-$APP_VER
mkdir ../install
./configure --prefix=$APP_DIR/install --with-pgport=${1}
make
make install


# build pgbench benchmark
cd contrib/pgbench
make
cp pgbench $APP_DIR/install/bin


# config postgresql
cd $APP_DIR/install
bin/pg_ctl init -D $APP_DIR/install/data
bin/pg_ctl start -D $APP_DIR/install/data
sleep 2
bin/createuser root
bin/pg_ctl stop -D $APP_DIR/install/data

