#! /bin/sh
# too build a concoord, at first you need install python setup_tools in your machine, it will automatically solve the dependencies of the concoord in the setup.py

wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
python ez_setup.py --user
cd ..
cd ..
cd concoord
sudo python setup.py install

