#!/bin/bash
if [ -z $1 ]; then
        # No ip address
        echo "Usage: <./client-test 128.59.17.172 9000>"
        exit 1
fi

if [ -z $2 ]; then
        # No port number
        echo "Usage: <./client-test 128.59.17.172 9000>"
        exit 1
fi

IP=$1;
PORT=$2;

cd $MSMR_ROOT/apps/mysql
LD_LIBRARY_PATH=mysql-install/lib/mysql/ \
sysbench-install/bin/sysbench \
        --mysql-host=$IP \
        --mysql-port=$PORT \
        --mysql-user=root \
        --test=oltp \
        --oltp-table-size=20000 \
        --oltp-table-name=sbtest \
        --mysql-table-engine=InnoDB \
        --mysql-engine-trx=yes \
        --mysql-db=sysbench_db \
        prepare


#killall -9 mysqld

