#!/bin/bash
if [ -z $1 ]; then
        # No version number
        echo "Usage: <./client-test 127.59.17.172>"
        exit 1
fi

IP=$1;

LD_LIBRARY_PATH=mysql-install/lib/mysql/ \
sysbench-install/bin/sysbench \
        --mysql-host=$IP \
        --mysql-port=7000 \
        --mysql-user=root \
        --test=oltp \
        --oltp-table-size=20000 \
        --oltp-table-name=sbtest \
        --mysql-table-engine=InnoDB \
        --mysql-engine-trx=yes \
        --mysql-db=sysbench_db \
        prepare


#killall -9 mysqld

