#!/bin/bash

IP=$1;

LD_LIBRARY_PATH=mysql-install/lib/mysql/ \
sysbench-install/bin/sysbench \
        --mysql-host=$IP \
        --mysql-port=7000 \
        --mysql-user=root \
        --test=oltp \
        --oltp-table-size=20000 \
        --oltp-table-name=sbtest \
        --mysql-table-engine=InnoDB \
        --mysql-engine-trx=yes \
        --mysql-db=sysbench_db \
        prepare


#killall -9 mysqld

