#!/bin/bash
#killall -9 server.out sysbench mysqld mysqld_safe &> /dev/null
sudo rm /tmp/mysql.sock

cd $MSMR_ROOT/apps/mysql
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so \
./mysql-install/libexec/mysqld --defaults-file=./my.cnf &> out.txt &
sleep 1;

echo ""
echo "Mysqld has started. Please remember to kill me ASAP after this sample run: killall -9 mysqld;"
echo ""
