#!/bin/bash

V=0.12.1

cd $MSMR_ROOT/apps/mediatomb/
rm -rf mediatomb-$V install .mediatomb

if [ ! -f mediatomb-$V.tar.gz ];
then
	wget http://downloads.sourceforge.net/mediatomb/mediatomb-$V.tar.gz
fi
tar zxvf mediatomb-$V.tar.gz
cd mediatomb-$V
./configure --prefix=$MSMR_ROOT/apps/mediatomb/install/

sed -e 's/search/this->search/g' src/hash/dso_hash.h > bak.h
mv bak.h src/hash/dso_hash.h

sed -e 's/search/this->search/g' src/hash/dbo_hash.h > bak.h
mv bak.h src/hash/dbo_hash.h

sed -e 's/search/this->search/g' src/hash/dbr_hash.h > bak.h
mv bak.h src/hash/dbr_hash.h

sed -e 's/#include "nil.h"/#include <cstddef>\n#include "nil.h"/g' src/zmm/zmm.h > bak.h
mv bak.h src/zmm/zmm.h

make -j `nproc`
make install

# generate database. you can also manually rerun this script for re generating database.
cd $MSMR_ROOT/apps/mediatomb/
./generate-database
