#!/bin/bash

if [ ! $1 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

if [ ! $2 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

NUM_THREADS=1
cd $MSMR_ROOT/apps/mediatomb

# Note: the -m $PWD option is for setting up the server with the
# config database MSMR_ROOT/apps/mediatomb/.mediatomb
x=1
echo "Starting $NUM_THREADS parallel connections to ask mediatomb server to transcode an avi file to mp4."
while [ $x -le $NUM_THREADS ];
do
  echo "Starting the $x client"
  x=`expr $x + 1`
  time wget -O result$x.mp4 \
	http://$1:$2/content/media/object_id/8/res_id/none/pr_name/vlcmpeg/tr/1 &
done
