#! /bin/bash
#run some test for the program
#to be added

#start two replicas,one is leader,the leader should ping others periodically and then we kill the leader, the other node should notice the loss of connection with the leader and initial a leader election

check_output(){
    
    LOG_NAME=${FILEPATH}/log/${TEST_NAME}_1_${NO}${LOG_SUFFIX}
    RESULT=$(grep "Lost.*Leader" ${LOG_NAME} | wc -l)
    if [ "${RESULT}" -eq "0" ];then
        exit 1
    else
        exit 0
    fi
}

TEST_NAME=$(basename $0)
NO=${1}

#echo "==========Ping Test =========="

CUR_DIR=$(pwd)
rm -rf ${CUR_DIR}/.db

LOG_SUFFIX=".log"

SLEEP_TIME=10

SECONDARIES_SIZE=1

#do not re-compile
:<<'END'
cd ..
make clean 
make
cd ${CUR_DIR}
END

if [ ! -e ${CUR_DIR}/${TEST_NAME} ];then
    FILEPATH=${CUR_DIR}/test
else
    FILEPATH=${CUR_DIR}
fi

if [ ! -e ${FILEPATH}/${TEST_NAME} ];then
    echo ${CUR_DIR}
    echo ${FILEPATH}
    echo "Script Execution Path Error"
    exit 1
fi


if [ ! -d ${FILEPATH}/log ];then
    mkdir ${FILEPATH}/log
fi

exec 2>${FILEPATH}/log/ping_test_err_${NO}

export LD_LIBRARY_PATH=${FILEPATH}/../.local/lib

#echo "The Log File Will Be Stored In ${FILEPATH}/log/${TEST_NAME}_*_${NO}"
#echo "Now We Start The Leader"
${FILEPATH}/../target/server.out -n 0 -m s -c ${FILEPATH}/../target/nodes.cfg &>${FILEPATH}/log/${TEST_NAME}_0_${NO}${LOG_SUFFIX}  &
PRIMARY_PID=$!

#echo "Now We Start Other Nodes"

for i in $(seq ${SECONDARIES_SIZE});do
    ${FILEPATH}/../target/server.out -n ${i} -m r -c ${FILEPATH}/../target/nodes.cfg &>${FILEPATH}/log/${TEST_NAME}_${i}_${NO}${LOG_SUFFIX} &
    declare NODE_${i}=$!
done

:<<'DEBUG'
for i in $(echo ${!NODE*});do
    echo "${!i}"
done
DEBUG

#echo "Sleep Some Time"
sleep ${SLEEP_TIME}

#echo "Kill The Leader"
kill -15 ${PRIMARY_PID} &>/dev/null

#echo "Sleep Some Time"
sleep ${SLEEP_TIME}

for i in $(echo ${!NODE*});do
    kill -15 ${!i} &>/dev/null
done

check_output

