#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# test to connect apache in container1 to containern

WORK_DIR=$MSMR_ROOT/apps/lxc/apache

cd $WORK_DIR

if [ "$1" == "" ]; then
  echo "<Usage> ./bunch_test_apache <number of instances>"
  exit 1
fi

echo ""
echo "This script requires root privilege, please input your password if prompted"
echo ""

# set bridge
BRIDGE_STATUS=$(sudo brctl show | grep virbr0)
if [ "$BRIDGE_STATUS" == "" ]; then
  sudo virsh net-start default
fi

# test if apache is built
if [ ! -f $MSMR_ROOT/apps/apache/install/bin/ab ]; then
  echo ""
  echo "Please proceed to m-smr/apps/apache to build apache first"
  exit 1
fi

for i in $(seq 1 $1);
do
  ./start_apache container$i
  sleep 5
  IP=$(sudo lxc-info -n container$i | grep IP | awk '{ print $2 }')
  $MSMR_ROOT/apps/apache/install/bin/ab -n 100 -c 10 http://$IP:80/
  ./stop_apache container$i
  sleep 5
done
