#!/bin/bash

cd $MSMR_ROOT/apps/ssdb

#killall -9 ssdb-server ssdb-bench
rm -rf ./ssdb-master/var/ssdb.pid
echo "" > ssdb-master/log.txt

LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so \
./ssdb-master/ssdb-server ./ssdb-master/ssdb.conf &> out.txt &

sleep 1
