#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# variables
APP_VER=2.6.5
APP_DIR=$MSMR_ROOT/apps/mongodb
NUMCPU=`nproc`

# working folder
cd $APP_DIR

# remove folders
rm -rf mongodb-src-r$APP_VER
rm -rf install
rm -rf ycsb-0.1.4

# download and extract
if [ ! -f mongodb-src-r$APP_VER.tar.gz ]; then
    wget http://downloads.mongodb.org/src/mongodb-src-r$APP_VER.tar.gz
fi
tar zxvf mongodb-src-r$APP_VER.tar.gz

# build
cd mongodb-src-r$APP_VER
scons mongod mongo -j $NUMCPU
mkdir ../install
mkdir ../install/bin
mkdir ../install/data
cp mongod ../install/bin
cp mongo ../install/bin
cd ../
tar zcvf install.tar.gz install

# download benchmark
curl -O https://cloud.github.com/downloads/brianfrankcooper/YCSB/ycsb-0.1.4.tar.gz
tar zxvf ycsb-0.1.4.tar.gz
cd ycsb-0.1.4
mvn clean package

# prepare for database.
cd $MSMR_ROOT/apps/mongodb/sysbench-mongodb
./prepare-sysbench
