#!/bin/bash

killall -9 clamd
cd $MSMR_ROOT/apps/clamav/

L2D_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so \
./install/sbin/clamd --config-file=./clamd.conf &> out.txt

echo "Clamd has started, you could run: ps -ef | grep clamd. Please kill it after use."
