#!/bin/bash

#
# Copyright (c) 2013,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

cd $XTERN_ROOT/apps/ExaCT
SOFTWARE="ExaCT_Proxy_Apps_20120322"
rm -rf $SOFTWARE
rm exp_cns_nospec* multigrid_c* vodeDriver *.fab
if [ ! -f $SOFTWARE.tgz ]; then
	echo "Source file missing, please register and download it at http://exactcodesign.org/proxy-app-software/"
	exit 1
fi
tar -xvzf $SOFTWARE.tgz 
patch -p0 < makefile_and_fix.patch

cd $SOFTWARE/BoxLib
export BOXLIB_HOME=`pwd`

ARCH=`uname -m`
GCCLIB=""
if [ "$ARCH" == "x86_64" ]; then
  GCCLIB="$XTERN_ROOT/apps/openmp/install/lib64"
else
  GCCLIB="$XTERN_ROOT/apps/openmp/install/lib"
fi

ln -s $GCCLIB/libgomp.a  &> /dev/null
ln -s $GCCLIB/libgfortran.a  &> /dev/null
ln -s $GCCLIB/libstdc++.a &> /dev/null

export PATH=$XTERN_ROOT/apps/openmp/install/bin:$PATH
cd Tutorials
pushd WaveEquation_C
make -j5 -f GNUmakefile
popd
pushd MultiGrid_C
make -j5 -f GNUmakefile
popd
pushd Exp_CNS_NoSpec
make -j5 -f GNUmakefile
popd

cd $BOXLIB_HOME/../Combustion/Chemistry/bin/vodeDriver
make -j5 -f GNUmakefile
cd $XTERN_ROOT/apps/ExaCT
ln -s $SOFTWARE/BoxLib/Tutorials/MultiGrid_C/main3d.Linux.gcc.gfortran.OMP.ex multigrid_c
ln -s $SOFTWARE/BoxLib/Tutorials/MultiGrid_C/inputs.3d multigrid_c_inputs.3d
ln -s $SOFTWARE/BoxLib/Tutorials/Exp_CNS_NoSpec/main.Linux.gfortran.omp.exe exp_cns_nospec
ln -s $SOFTWARE/BoxLib/Tutorials/Exp_CNS_NoSpec/inputs_3d exp_cns_nospec_inputs.3d
ln -s $SOFTWARE/Combustion/Chemistry/bin/vodeDriver/cdvode2d.Linux.g++.gfortran.OMP.ex vodeDriver
ln -s $SOFTWARE/Combustion/Chemistry/bin/vodeDriver/drm19_0700.fab .
echo "done!!"
