#!/bin/bash
cd $XTERN_ROOT/apps/ExaCT
SOFTWARE="ExaCT_Proxy_Apps_20120322"

cd $SOFTWARE/BoxLib/Tutorials/Exp_CNS_NoSpec/
rm -rf out* serializer.log

#Your Executable file name may be different
#Run with xtern
LD_PRELOAD=$XTERN_ROOT/dync_hook/interpose.so ./main.Linux.gfortran.omp.exe inputs_3d

#Run non-det
LD_PRELOAD=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so ./main.Linux.gfortran.omp.exe inputs_3d
