#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


APP_DIR=$MSMR_ROOT/apps/redis

cd $APP_DIR/install
bin/redis-server $APP_DIR/install/redis.conf
sleep 2

bin/redis-benchmark -p 6679 -c 20 -n 100000

kill $(cat redis.pid)

#cd $XTERN_ROOT/apps/redis
#rm -rf out* *.log rr-* random-*
#killall -9 redis-server redis-benchmark &> /dev/null
#PRELOAD_LIB=""
#SCHED=""

#runRedis(){
#	# Start the server.
#	LD_PRELOAD=$PRELOAD_LIB ./redis-server redis-threads.conf > #server-$SCHED.log 2>&1 &
#	sleep 5
#
#	# Start the benchmark (client). Can change workload here.
#	./redis-benchmark -n 100000 > benchmark-$SCHED.log 2>&1
#	sleep 2
#	mv out out-$SCHED
#	$XTERN_ROOT/eval/draw-time-chart.pl ./out-$SCHED
#	mv time-chart.txt $SCHED-time-chart.txt
#
#	# Clean.
#	killall -9 redis-server &> /dev/null
#}

#SCHED="rr"
#PRELOAD_LIB=$XTERN_ROOT/dync_hook/interpose.so
#echo "Running redis with $PRELOAD_LIB..."
#runRedis;

#SCHED="random"
#PRELOAD_LIB=$XTERN_ROOT/eval/rand-intercept/rand-intercept.so
#echo "Running redis with $PRELOAD_LIB..."
#runRedis;
