#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# apache benchmark (ab) source code at: httpd-2.4.10/support/ab.c

# variables
APR_VER=1.5.1
UTIL_VER=1.5.4
HTTPD_VER=2.4.10
PCRE_VER=8.36
APP_DIR=$MSMR_ROOT/apps/apache

# working folder
cd $APP_DIR

# remove folder
rm -rf httpd-$VER
rm -rf install
rm -rf pcre
rm -rf pcre-$PCRE_VER

# download and extract
if [ ! -f httpd-$HTTPD_VER.tar.gz ]; then
    wget http://mirror.metrocast.net/apache//httpd/httpd-$HTTPD_VER.tar.gz
fi
tar zxvf httpd-$HTTPD_VER.tar.gz

# build dependencies
if [ ! -f pcre-$PCRE_VER.tar.gz ]; then
    wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$PCRE_VER.tar.gz
fi
tar pcre-$PCRE_VER.tar.gz
cd pcre-$PCRE_VER
./configure --prefix=$APP_DIR/pcre
make
make install

cd ../httpd-$HTTPD_VER/srclib

if [ ! -f apr-$APR_VER.tar.gz ]; then
    wget http://apache.mirrors.pair.com//apr/apr-$APR_VER.tar.gz
fi
tar zxvf apr-$APR_VER.tar.gz
mv apr-$APR_VER apr

if [ ! -f apr-util-$UTIL_VER.tar.gz ]; then
    wget http://apache.mirrors.pair.com//apr/apr-util-$UTIL_VER.tar.gz
fi
tar zxvf apr-util-$UTIL_VER.tar.gz
mv apr-util-$UTIL_VER apr-util

# build
cd ../
mkdir ../install
./configure --prefix=$APP_DIR/install --with-included-apr --enable-mods-shared=all --with-pcre=$APP_DIR/pcre
make
make install

# change conf file
cd $MSMR_ROOT/apps/apache/install/conf
sed -e "s/Listen 80/Listen 7000/g"  httpd.conf > httpd.conf.tmp
mv httpd.conf.tmp httpd.conf

