#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# apache benchmark (ab) source code at: httpd-2.4.10/support/ab.c

# variables
HTTPD_VER=2.2.11
PHP_VER=5.4.0
APP_DIR=$MSMR_ROOT/apps/apache

# working folder
cd $APP_DIR

# remove folder
rm -rf httpd-$HTTPD_VER
rm -rf install
rm -rf php-$PHP_VER
rm -rf install-php

# download and extract
if [ ! -f httpd-$HTTPD_VER.tar.gz ]; then
    #wget http://mirror.metrocast.net/apache//httpd/httpd-$HTTPD_VER.tar.gz
    wget https://archive.apache.org/dist/httpd/httpd-$HTTPD_VER.tar.gz
fi
tar zxvf httpd-$HTTPD_VER.tar.gz

cd $APP_DIR/httpd-$HTTPD_VER
patch -p1 < ../add-detach-for-pod-check-thread.patch
patch -p1 < ../add-soba-httpd.patch

# build
#./configure --prefix=$APP_DIR/install --with-included-apr --enable-mods-shared=all \
#	--with-pcre=$APP_DIR/pcre \
#	--enable-mpm=worker --enable-module=all
CFLAGS="-g -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot" \
./configure \
        --with-mpm=worker \
        --prefix=$APP_DIR/install \
        --with-devrandom=/dev/urandom \
        --disable-proxy \
        --with-included-apr

make -j16
make install

# build php
cd $APP_DIR
if [ ! -f php-$PHP_VER.tar.gz ]; then
	wget http://ftp.ntu.edu.tw/tmp/php/distributions/php-$PHP_VER.tar.gz
fi
tar zxvf php-$PHP_VER.tar.gz
cd php-$PHP_VER
patch -p1 < ../add-soba-php.patch
CFLAGS="-g -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot" \
	./configure --prefix=$MSMR_ROOT/apps/apache/install-php --with-apxs2=$MSMR_ROOT/apps/apache/install/bin/apxs --disable-dom --disable-simplexml
make -j16
make install


# change conf file
cd $MSMR_ROOT/apps/apache/install/conf
sed -e "s/Listen 80/Listen 7000/g"  httpd.conf > httpd.conf.tmp
mv httpd.conf.tmp httpd.conf
echo "ServerName localhost" >> httpd.conf
echo "ServerLimit 1" >> httpd.conf
echo "ThreadsPerChild 8" >> httpd.conf
cp $MSMR_ROOT/apps/apache/test.php $MSMR_ROOT/apps/apache/install/htdocs/
cp $MSMR_ROOT/apps/apache/test.php ~/

# add php filter.
sed -e "s/#AddType text\/html \.shtml/AddType application\/x-httpd-php \.php/g" httpd.conf > httpd.conf.tmp
mv httpd.conf.tmp httpd.conf
